### ISSUE TITLE
Feature request: Relayer status endpoint

### ISSUE THREAD

**Issue by R0bi7** [icon-project/btp2#35]
**Describe the issue**
Currently, it is not possible to check status of testnet relayers (processing queue, latest state, etc..).

What I would like to see is an endpoint where at least following data can be retrieve:
- status of the relay queue (i.e. messages observed but not relayed further, block heights to be checked, etc..)
- latest head block height per chain observed (i.e. up to which blockheight relayer observed)
- health of relayer (i.e. is relayer catching up, up to speed, stale, etc..)

I think this data can be very beneficial for testing purposes as well as further dApp development.

**Comment by mksong76** [comment]
We don't want to expose any service port in Relay to prevent any hacking or DOS.
So, the status of the relay can't be through the endpoint. Instead of it, we can use the status of BMC to meet your requirements.

**Number of pending messages**

The number of messages in pending status can be get by checking sequence numbers. If all messages are properly delivered, then the TX sequence number of the sender and the RX sequence number of the receiver should be the same. Otherwise, the difference is the number of pending messages.

**Monitoring block height**

This information can't be retrieved without accessing the relays.

**Health of relay**

We see lots of problems with relays. Even though it's alive, sometimes it doesn't deliver messages properly. So we think that it's not a good idea to check whether it's alive or not. Instead of it, we try to estimate delivery latency, then check whether the delivery delay exceeds the estimated time. To do this, we will monitor sequence number changes. And check the delay in message delivery.

The result is the following monitoring site.
Please check it out, https://testnet.btp2.24x365.online/
